---
- hosts: privateVPN
  gather_facts: False
  vars:
    ca_name: unused
    crypto_curve: secp256k1
  tasks:
    - name: Create installurl with repos
      raw: echo "http://mirror.switch.ch/ftp/pub/OpenBSD" > /etc/installurl
      tags:
        - update_installurl
        - basesystem_config
    - name: Install python needed by ansible
      raw: pkg_add python%2.7
      tags:
        - basesystem_config
        - install_python
    - name: Link python2.7 as default
      raw: ln -s /usr/local/bin/python2.7 /usr/bin/python
      ignore_errors: yes
    - name: Check numer of CPU present in the system
      shell: sysctl -n hw.ncpu
      register: ncpu
      tags:
        - get_generic_obj
        - basesystem_config
    - name: Check if kernel is MP or SP
      shell: uname -v | awk 'BEGIN{RS="\0777";FS=".MP#"} { print NF-1 } '
      register: mp
      tags:
        - get_generic_obj
        - basesystem_config
    - name: Get GENERIC non-MP object files for OpenBSD 6.2. See README file why it's done
      get_url:
        url: https://onefellow.com/download/GENERIC62.tar.gz
        dest: /usr/share/compile/GENERIC62.tar.gz
        checksum: sha256:649d5297933abb5a73593ff07c319511dc9a34430b362b7e8aeb2c3e521d4d7a
      when:
        - ncpu.stdout == "1"
        - mp.stdout == "1"
      tags:
        - get_generic_obj
        - basesystem_config
    - name: Extract GENERIC obj into place
      shell: tar -zxvf /usr/share/compile/GENERIC62.tar.gz -C /usr/share/compile/
      when:
        - ncpu.stdout == "1"
        - mp.stdout == "1"
      tags:
        - get_generic_obj
        - basesystem_config
    - name: Copy SP kernel only when MP detected on SP platform
      shell: cp /bsd.sp /bsd
      when:
        - ncpu.stdout == "1"
        - mp.stdout == "1"
      tags:
        - get_generic_obj
        - basesystem_config
    - name: Update kernel hash to make KARL working with SP kernel
      shell: sha256 -h /var/db/kernel.SHA256 /bsd
      when:
        - ncpu.stdout == "1"
        - mp.stdout == "1"
      tags:
        - get_generic_obj
        - basesystem_config
    - name: Rebooting machine to activate new SP kernel
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      async: 1
      poll: 0
      ignore_errors: true
      when:
        - ncpu.stdout == "1"
        - mp.stdout == "1"
      tags:
        - get_generic_obj
        - basesystem_config
    - name: Waiting for machine to get back (this make take some time...)
      local_action: wait_for host={{ ansible_ssh_host }} state=started port=22 delay=120 timeout=120
      become: false
      when:
        - ncpu.stdout == "1"
        - mp.stdout == "1"
      tags:
        - get_generic_obj
        - basesystem_config
    - name: Update OpenBSD base system (can take lot of time)
      shell: syspatch
      register: bsd_updated
      tags:
        - update_bsd
    - name: Remove unessesery software
      openbsd_pkg: name=opensmtpd state=absent
      tags:
        - remove_packages
    - name: Disable and Stop services
      shell: rcctl disable {{ item }} ; rcctl stop {{ item }}
      with_items:
        - smtpd
        - sndiod
      tags:
        - disable_services
    - name: Detect interface name
      shell: basename /etc/hostname.*|cut -d. -f2
      register: ifname
      tags:
        - install_packages
        - detect_iface
        - is_aws
      # Assume, possibly wrong... that xnf0 is AWS specyfic as xnf0 is xen ifname,
    - name: Install dhcpcd only on AWS (xnf0) instance
      openbsd_pkg: name=dhcpcd state=present
      when: ifname.stdout == "xnf0"
      tags:
        - install_packages
        - detect_iface
    - name: Use dhcpcd only for IPv6
      shell: echo -e "ipv6only\nnohook resolv.conf" >> /etc/dhcpcd.conf
      when: ifname.stdout == "xnf0"
      tags:
        - install_packages
        - basesystem_config
        - detect_iface
    - name: Enable dhcpcd
      shell: rcctl enable dhcpcd
      when: ifname.stdout == "xnf0"
      tags:
        - install_packages
        - basesystem_config
        - detect_iface
    - name: Rebooting machine after updates
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      async: 1
      poll: 0
      ignore_errors: true
      when: bsd_updated.changed
    - name: Waiting for machine to get back (this make take some time...)
      local_action: wait_for host={{ ansible_ssh_host }} state=started port=22 delay=120 timeout=120
      become: false
      when: bsd_updated.changed
    - name: Install required packages
      openbsd_pkg: name={{ item }} state=present
      with_items:
        - easy-rsa
        - openvpn--
        - bash
        - apg
      tags:
        - install_packages
        - basesystem_config
    - name: Get openup
      shell: ftp -MVo /usr/bin/openup https://stable.mtier.org/openup;chmod +x /usr/bin/openup
      tags:
        - update_openup
        - install_openup
    - name: Update packages using openup
      shell: /usr/bin/openup -N
      tags:
        - update_packages
    - name: Create some dirs
      file: path={{ item.dir }} owner={{ item.owner }} group={{ item.group }} state=directory
      with_items:
        - { dir: /etc/openvpn, owner: root, group: wheel }
        - { dir: /etc/openvpn/export, owner: root, group: wheel }
        - { dir: /etc/openvpn/jail, owner: root, group: wheel }
        - { dir: /etc/openvpn/jail/ccd, owner: root, group: wheel }
        - { dir: /etc/openvpn/jail/tmp, owner: root, group: wheel }
        - { dir: /etc/openvpn/status, owner: root, group: wheel }
        - { dir: /etc/openvpn/export/archives, owner: root, group: wheel }
        - { dir: /etc/openvpn/export/privateVPN-Desktop.visc, owner: root, group: wheel }
      tags:
        - create_dirs
        - basesystem_config
    - name: Symlink bash (yes i like bash)
      file: state=link src=/usr/local/bin/bash dest=/bin/bash force=yes
    - name: Symlink easy-rsa
      file: state=link src=/usr/local/share/easy-rsa dest=/etc/openvpn/easy-rsa force=yes
    - name: Copy config files
      copy: src=files/{{ item.src }} dest={{ item.dst}} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} #mode="u+rwx,go-w"
      with_items:
        - { src: privateVPN.conf, dst: /etc/openvpn/privateVPN.conf, owner: root, group: wheel, mode: "u+rw,go-rw" }
        - { src: openvpn.init, dst: /etc/rc.d/openvpn, owner: root, group: wheel, mode: "ugo+x,go-w" }
        - { src: rc.conf.local, dst: /etc/rc.conf.local, owner: root, group: wheel, mode: "u+rw,go+r" }
        - { src: gen_config.sh, dst: /etc/openvpn/export, owner: root, group: wheel, mode: "u+rwx,go-rwx" }
        - { src: privateVPN-Desktop.visc/config.conf, dst: /etc/openvpn/export/privateVPN-Desktop.visc/config.conf, owner: root, group: wheel, mode: "u+rwx,go-rwx" }
        - { src: privateVPN-Mobile.ovpn.template, dst: /etc/openvpn/export/privateVPN-Mobile.ovpn.template, owner: root, group: wheel, mode: "u+rwx,go-rwx" }
        - { src: unbound.conf, dst: /var/unbound/etc/unbound.conf, owner: root, group: wheel, mode: "u+rw,go+r" }
      tags:
        - copy_configs
        - basesystem_config
    - name: Generate pf config file
      template: src=files/pf.j2 dest=/etc/pf.conf owner=root group=wheel
      tags:
        - copy_configs
    - name: Update listening IP - Others
      shell: ifconfig {{ ifname.stdout }}|grep inet|grep -v inet6|awk '{ print $2}'|xargs -I xxx sed -i 's/[[:<:]]LISTEN_IP[[:>:]]/xxx/g'
               /etc/openvpn/export/privateVPN-Desktop.visc/config.conf
               /etc/openvpn/export/privateVPN-Mobile.ovpn.template
      when: ifname.stdout == "vio0"
      tags:
        - update_templates
        - copy_configs
    - name: Update listening IP - AWS
      shell: ftp -MVo - http://169.254.169.254/latest/meta-data/public-ipv4|xargs -I xxx sed -i 's/[[:<:]]LISTEN_IP[[:>:]]/xxx/g'
               /etc/openvpn/export/privateVPN-Desktop.visc/config.conf
               /etc/openvpn/export/privateVPN-Mobile.ovpn.template
      when: ifname.stdout == "xnf0"
      tags:
        - update_templates
        - copy_configs
    - name: Let's do some sed's on the template files
      shell: "{{ item }}"
      with_items:
        - ifconfig {{ ifname.stdout }} | grep inet | grep -v inet6 | awk '{ print $2}' | xargs -I xxx sed -i 's/[[:<:]]LISTEN_IP[[:>:]]/xxx/g'
            /etc/openvpn/privateVPN.conf
            /etc/pf.conf
        - hostname | xargs -I xxx sed -i s/SERVER_CERT/PrivateVPN-xxx/g /etc/openvpn/privateVPN.conf
        - w -h|grep root|awk '{print $3}'|xargs -I xxx sed -i s/SSH_ADMIN/xxx/g /etc/pf.conf
      tags:
        - update_templates
        - copy_configs
      # Have better idea? Create pull request...
    - name: Detect if IPv6 is up on {{ ifname.stdout }}
      shell: ifconfig {{ ifname.stdout }}|sed -n '/inet6/p'|grep -v "inet6 fe80:"|wc -l|sed -e 's/^[ \t]*//'
      register: ipv6is
      tags:
        - reload_pf
    - name: Get IPv6 address
      shell: ifconfig {{ ifname.stdout }} | grep inet6 | egrep -v -e "inet6 fe80:" -e autoconfprivacy | awk '{ print $2}'
      register: ipv6addr
      when: ipv6is.stdout != "0"
      tags:
        - reload_pf
    - name: If IPv6 is present add additional rules to pf and place IPv6 address
      shell: "{{ item }}"
      with_items:
        - echo "pass out on {{ ifname.stdout }} from fdd5:b0c4:f9fb:fa1f::/64 to any nat-to \$ext_ip_6" >> /etc/pf.conf
        - sed -i s/LISTEN_IPv6/{{ ipv6addr.stdout }}/g /etc/pf.conf
      when: ipv6is.stdout != "0"
      tags:
        - reload_pf
    - name: Reload pf
      command: pfctl -f /etc/pf.conf
      tags:
        - reload_pf
    - name: Easy-RSA - Initialize and Generate PKI/CA/Server Certificate
      shell: chdir=/etc/openvpn/easy-rsa/ {{ item }}
      with_items:
        - ./easyrsa init-pki
        - ./easyrsa gen-dh
        - apg -a 1 -m 6 -MCL -n1 | xargs -I xxx ./easyrsa --batch --req-cn="privateVPN CA (xxx)" --use-algo=ec --curve={{ crypto_curve }} build-ca nopass
        - hostname | xargs -I xxx ./easyrsa --use-algo=ec --curve={{ crypto_curve }} --ns-cert=yes build-server-full "PrivateVPN-xxx" nopass
      tags:
        - create_pki
    - name: Create one sample set of Client certificates. John have Desktop while Barbara have iPhone
      shell: chdir=/etc/openvpn/easy-rsa/ {{ item }}
      with_items:
        - ./easyrsa --use-algo=ec --curve={{ crypto_curve }} build-client-full privateVPN-Desktop-JohnDoe nopass
        - ./easyrsa --use-algo=ec --curve={{ crypto_curve }} build-client-full privateVPN-Mobile-BarbaraDoe nopass
      tags:
        - gen_client_certs
    - name: Create shared-secret for tls-crypt
      shell: openvpn --genkey --secret /etc/openvpn/easy-rsa/pki/ta.key
      tags:
        - gen_ta
    - name: Generate CRL
      shell: cd /etc/openvpn/easy-rsa/; ./easyrsa gen-crl ; cp pki/crl.pem /etc/openvpn/jail/crl.pem
      tags:
        - update_crl
    - name: Fix CRL permissions so jailed openvpn can read content
      file: path=/etc/openvpn/jail/crl.pem mode=0644
      tags:
        - update_crl
    - name: Generate SHA256 from CA certificate
      shell: openssl x509 -in /etc/openvpn/easy-rsa/pki/ca.crt -noout -sha256 -fingerprint|cut -d= -f2
      register: ca_sha2
      tags:
        - get_ca_sha2
        - update_ca_hash
    # verify-hash is not yet supported on iOS but we generate it anyway for future use
    - name: Generate SHA1 from CA certificate
      shell: openssl x509 -in /etc/openvpn/easy-rsa/pki/ca.crt -noout -sha1 -fingerprint|cut -d= -f2
      register: ca_sha1
      tags:
        - get_ca_sha1
        - update_ca_hash
    - name: Put SHA256 and SHA1 into client configurations
      shell: "{{ item }}"
      with_items:
        - sed -i s/CA_HASH/{{ ca_sha2.stdout }}/g /etc/openvpn/export/privateVPN-Desktop.visc/config.conf
        - sed -i s/CA_HASH/{{ ca_sha1.stdout }}/g /etc/openvpn/export/privateVPN-Mobile.ovpn.template
      tags:
        - update_ca_hash
    # I do not care for other entries in sysctl.conf as we do it for this playbook purpose, feel free to make it better ;)
    - name: Enable forwarding and make it permement
      shell: "{{ item }}"
      with_items:
        - echo "net.inet.ip.forwarding=1" > /etc/sysctl.conf
        - echo "net.inet6.ip6.forwarding=1" >> /etc/sysctl.conf
        - sysctl net.inet.ip.forwarding=1
        - sysctl net.inet6.ip6.forwarding=1
      tags:
        - enable_forwarding
    - name: Use localhost as primary DNS server, and Google as secondary
      shell: "{{ item }}"
      with_items:
        - echo "prepend domain-name-servers 127.0.0.1,8.8.8.8,8.8.4.4 ;" > /etc/dhclient.conf ;
        - echo "nameserver 127.0.0.1" > /etc/resolv.conf
        - pgrep dhclient | while read dhcpds ; do kill -HUP $dhcpds; done
      tags:
        - update_resolvconf
    - name: Configure unbound
      shell: "{{ item }}"
      with_items:
        - sed -i '/auto-trust-anchor-file/s/#//g' /var/unbound/etc/unbound.conf
    - name: Update root hints file
      get_url:
        url: https://www.internic.net/domain/named.root
        dest: /var/unbound/db/named.cache
        mode: 0644
      tags:
        - update_hints
        - install_unbound
    # ToDO: fix BSD init services to make it compatibile properly
    - name: Enable services ans start them
      shell: rcctl {{ item }}
      with_items:
        - enable openvpn
        - start openvpn
        - enable unbound
        - start unbound
      tags:
        - enable_services
    - name: Pack Client Configs (one for iPhone OpenVPN and second for Viscosity Desktop VPN)
      shell: chdir=/etc/openvpn/export/ {{ item }}
      with_items:
        - ./gen_config.sh privateVPN-Desktop-JohnDoe
        - ./gen_config.sh privateVPN-Mobile-Barbara
      tags:
        - gen_package_vpn
